Repository andela/bp-esa-backend, pull requests merged in 2019-09, with the labels that each got.

#129 Eliminate rate limit error when running test
  server/helpers/redis.js
  server/mockAndelaApi/index.js
  server/modules/slack/slackIntegration.js
  test/endpoints/mockAndelapi.test.js
  test/helpers/helpers.test.js
  test/jobs/executejobs.test.js
  test/mocks/slack.js
  test/modules/slackIntegration.spec.js
Labels: Finished

#125 #167486160 Protect routes on the backend to permit only authenticated users
  package.json
  server/helpers/authHelpers.js
  server/index.js
  server/middleware/auth.js
  server/routes/automationRouter.js
  server/routes/index.js
  test/endpoints/automations.test.js
  test/endpoints/partner.test.js
  test/endpoints/workerStatus.test.js
  test/middleware/auth.test.js
  test/mockData/userPayload.js
Labels: Finished, Peer Review

#132 Add Functionality for creating and serving files to the frontend
  out.csv
  package.json
  server/controllers/automationController.js
  server/index.js
  server/reportFields.js
  server/routes/automationRouter.js
  test/endpoints/automations.test.js
Labels: Peer Review

#135 Ensure that the Noko automations are successful with the right token
  package.json
  server/jobs/onboarding/noko.js
  server/modules/noko/projects.js
  server/utils/helpers.js
  test/mocks/automations.js
  test/modules/moxios.axios.mocker.js
  test/modules/noko/projects.test.js
  test/utils/helpers.test.js
Labels: Peer Review

#133 bg(email): Fix the email limit
  .DS_Store
  server/modules/email/emailTransport.js
  test/mocks/slack.js
  test/modules/automation.test.js
  test/modules/slackIntegration.spec.js
Labels: Peer Review

#137 #167589981 Fix ES lint issues on the backend
  .eslintignore
  README.md
  package.json
  server/controllers/automationController.js
  server/helpers/redis.js
  server/index.js
  server/jobs/helpers.js
  server/jobs/index.js
  server/jobs/worker.js
  server/mockAndelaApi/index.js
  server/modules/email/emailModule.js
  server/modules/email/emailTransport.js
  server/modules/slack/slackIntegration.js
  server/reportFields.js
  test/mocks/slack.js
  test/modules/automation.test.js
Labels: Peer Review

#140 Reset changes Dockerfile
  Dockerfile
  scripts/entrypoint.sh
Labels: Peer Review

#136 Endpoint to fetch records of upselling partners
  .gitignore
  package.json
  server/controllers/automationController.js
  server/controllers/dashboardController.js
  server/controllers/workerStatus.js
  server/helpers/dateHelpers.js
  server/helpers/daysBetween.js
  server/helpers/paginationHelper.js
  server/middleware/validator.js
  server/routes/dashboardRouter.js
  server/routes/index.js
  server/utils/formatter.js
  test/endpoints/automations.test.js
  test/endpoints/dashboard.test.js
Labels: Peer Review, WIP

#142 #168061772: Create an endpoint for engagement trends
  server/controllers/automationStatsController.js
  server/controllers/dashboardController.js
  server/helpers/dateHelpers.js
  server/routes/dashboardRouter.js
  server/routes/index.js
  test/endpoints/engagementTrends.test.js
  test/modules/slackIntegration.spec.js
Labels: Peer Review
